---
name: jdtls
description: Java language server.
homepage: https://github.com/eclipse/eclipse.jdt.ls
licenses:
  - EPL-2.0
languages:
  - Java
categories:
  - LSP

source:
  id: pkg:generic/eclipse/eclipse.jdt.ls@v1.43.0
  download:
    - target: [darwin_x64, darwin_arm64]
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/archive/refs/tags/{{ version | strip_prefix "v" }}/jdtls.tar.gz
      config: config_mac/

    - target: [linux_x64, linux_x86]
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/archive/refs/tags/{{ version | strip_prefix "v" }}/jdtls.tar.gz
      config: config_linux/

    - target: linux_arm64
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/archive/refs/tags/{{ version | strip_prefix "v" }}/jdtls.tar.gz
      config: config_linux_arm/

    - target: win
      files:
        jdtls.tar.gz: https://github.com/nvim-java/release-jdtls/archive/refs/tags/{{ version | strip_prefix "v" }}/jdtls.tar.gz
      config: config_win/

schemas:
  lsp: vscode:https://raw.githubusercontent.com/redhat-developer/vscode-java/master/package.json

# In my case this provide Error
#bin:
#  jdtls: python:bin/jdtls

share:
  jdtls/plugins/: plugins/
  jdtls/config/: "{{source.download.config}}"
