---
name: jdtls
description: Java language server.
homepage: https://github.com/eclipse/eclipse.jdt.ls
licenses:
  - EPL-2.0
languages:
  - Java
categories:
  - LSP

source:
  id: pkg:generic/eclipse/eclipse.jdt.ls@v1.37.0
  download:
    - target: [darwin_x64, darwin_arm64]
      files:
        jdtls.tar.gz: https://download.eclipse.org/jdtls/milestones/{{ version | strip_prefix "v" }}/jdt-language-server-{{ version | strip_prefix "v" }}-202406271335.tar.gz
      config: config_mac/

    - target: [linux_x64, linux_x86]
      files:
        jdtls.tar.gz: https://download.eclipse.org/jdtls/milestones/{{ version | strip_prefix "v" }}/jdt-language-server-{{ version | strip_prefix "v" }}-202406271335.tar.gz
      config: config_linux/

    - target: linux_arm64
      files:
        jdtls.tar.gz: https://download.eclipse.org/jdtls/milestones/{{ version | strip_prefix "v" }}/jdt-language-server-{{ version | strip_prefix "v" }}-202406271335.tar.gz
      config: config_linux_arm/

    - target: win
      files:
        jdtls.tar.gz: https://download.eclipse.org/jdtls/milestones/{{ version | strip_prefix "v" }}/jdt-language-server-{{ version | strip_prefix "v" }}-202406271335.tar.gz
      config: config_win/

schemas:
  lsp: vscode:https://raw.githubusercontent.com/redhat-developer/vscode-java/master/package.json

bin:
  jdtls: python:bin/jdtls

share:
  jdtls/plugins/: plugins/
  jdtls/plugins/org.eclipse.equinox.launcher.jar: plugins/org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar
  jdtls/config/: "{{source.download.config}}"
