---
name: java-debug-adapter
description: The debug server implementation for Java. It conforms to the debugger adapter protocol.
homepage: https://github.com/nvim-java/vscode-java-debug-releases
licenses:
  - EPL-1.0
languages:
  - Java
categories:
  - DAP

source:
  id: pkg:github/microsoft/vscode-java-debug@0.50.0
  asset:
    file: artifacts.zip

share:
  java-debug-adapter/: extension/server/
  java-debug-adapter/com.microsoft.java.debug.plugin.jar: extension/server/com.microsoft.java.debug.plugin-{{version}}.jar
